### ISSUE TITLE
Compiling some if constant expressions with `Float` causes deep recursion

### ISSUE THREAD

**Issue by Rob23oba** [leanprover/lean4#6099]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

When using `#eval` with a function that returns a float and uses recursion, you sometimes get the error message `(kernel) deep recursion detected`:
```lean
def exampleNatToFloat (n : Nat) : Float :=
  if n.log2 > 0 then 1 else 0

#eval exampleNatToFloat 99999999 -- (kernel) deep recursion detected
#eval Repr.reprPrec (exampleNatToFloat 99999999) 1 -- (kernel) deep recursion detected
#eval (do pure (exampleNatToFloat 99999999) : IO Float) -- works on 4.14.0-rc1, fails on nightly
#eval Float.toString (exampleNatToFloat 99999999) -- works
```
When using a smaller number like 999, the interpreter instead takes really long to run.

### Versions

This is a recent regression, this worked in `4.13.0` but fails in `4.14.0-rc1`.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Rob23oba** [comment]
After investigating this issue, I found out that it seems to be a much more common issue than I thought.
This also applies to compiling some `if` expressions with a constant condition that uses a `Float`:
```lean
/--
error: (kernel) deep recursion detected
-/
#guard_msgs in
example :=
  if (
    if (30000000).log2 > 0 then 1 else 0 : Float
  ) < 0 then
    true
  else
    false
```
The actual error happens in [erase_irrelevant_fn](https://github.com/leanprover/lean4/blob/799b2b662825e646609963921f2c68489b2e664a/src/library/compiler/erase_irrelevant.cpp#L46).
Backtrace:
```
#23323 0x00007ffda109e37b in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23324 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23325 0x00007ffda1098de4 in lean::type_checker::whnf(lean::expr const&) ()
#23326 0x00007ffda109d567 in lean::type_checker::reduce_recursor(lean::expr const&, bool, bool) ()
#23327 0x00007ffda109e37b in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23328 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23329 0x00007ffda1098de4 in lean::type_checker::whnf(lean::expr const&) ()
#23330 0x00007ffda109d567 in lean::type_checker::reduce_recursor(lean::expr const&, bool, bool) ()
#23331 0x00007ffda109e37b in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23332 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23333 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23334 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23335 0x00007ffda109e3e6 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23336 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23337 0x00007ffda1098de4 in lean::type_checker::whnf(lean::expr const&) ()
#23338 0x00007ffda109d567 in lean::type_checker::reduce_recursor(lean::expr const&, bool, bool) ()
#23339 0x00007ffda109e37b in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23340 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23341 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23342 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23343 0x00007ffda109e3e6 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23344 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23345 0x00007ffda1098de4 in lean::type_checker::whnf(lean::expr const&) ()
#23346 0x00007ffda109d567 in lean::type_checker::reduce_recursor(lean::expr const&, bool, bool) ()
#23347 0x00007ffda109e37b in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23348 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23349 0x00007ffda1098de4 in lean::type_checker::whnf(lean::expr const&) ()
#23350 0x00007ffda10a71ff in lean::optional<lean::expr> lean::type_checker::reduce_bin_nat_op<lean_object* (lean_object*, lean_object*)>(lean_object* ( const&)(lean_object*, lean_object*), lean::expr const&) ()
#23351 0x00007ffda109f8de in lean::type_checker::reduce_nat(lean::expr const&) ()
#23352 0x00007ffda1098eee in lean::type_checker::whnf(lean::expr const&) ()
#23353 0x00007ffda10a76f6 in lean::optional<lean::expr> lean::type_checker::reduce_bin_nat_pred<bool (lean_object*, lean_object*)>(bool ( const&)(lean_object*, lean_object*), lean::expr const&) ()
#23354 0x00007ffda109f9a4 in lean::type_checker::reduce_nat(lean::expr const&) ()
#23355 0x00007ffda1098eee in lean::type_checker::whnf(lean::expr const&) ()
#23356 0x00007ffda109d567 in lean::type_checker::reduce_recursor(lean::expr const&, bool, bool) ()
#23357 0x00007ffda109e37b in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23358 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23359 0x00007ffda1098de4 in lean::type_checker::whnf(lean::expr const&) ()
#23360 0x00007ffda109d567 in lean::type_checker::reduce_recursor(lean::expr const&, bool, bool) ()
#23361 0x00007ffda109e37b in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23362 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23363 0x00007ffda1098de4 in lean::type_checker::whnf(lean::expr const&) ()
#23364 0x00007ffda109d567 in lean::type_checker::reduce_recursor(lean::expr const&, bool, bool) ()
#23365 0x00007ffda109e37b in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23366 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23367 0x00007ffda1098de4 in lean::type_checker::whnf(lean::expr const&) ()
#23368 0x00007ffda109d567 in lean::type_checker::reduce_recursor(lean::expr const&, bool, bool) ()
#23369 0x00007ffda109e37b in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23370 0x00007ffda109e441 in lean::type_checker::whnf_core(lean::expr const&, bool, bool) ()
#23371 0x00007ffda1098de4 in lean::type_checker::whnf(lean::expr const&) ()
#23372 0x00007ffda10fe82a in lean::mk_runtime_type(lean::type_checker::state&, lean::local_ctx const&, lean::expr) ()
#23373 0x00007ffda1135b8e in lean::erase_irrelevant_fn::mk_runtime_type(lean::expr) ()
#23374 0x00007ffda11363e3 in lean::erase_irrelevant_fn::visit_lambda_core(lean::expr, bool) ()
#23375 0x00007ffda11355c4 in lean::erase_irrelevant_fn::decidable_to_bool_cases(lean::buffer<lean::expr, 16ull> const&) ()
#23376 0x00007ffda1131c2a in lean::erase_irrelevant_fn::visit_cases_on(lean::expr const&, lean::buffer<lean::expr, 16ull>&) ()
#23377 0x00007ffda1130870 in lean::erase_irrelevant_fn::visit_app(lean::expr const&) ()
#23378 0x00007ffda112ffb9 in lean::erase_irrelevant_fn::visit(lean::expr const&) ()
#23379 0x00007ffda1131370 in lean::erase_irrelevant_fn::visit_let(lean::expr) ()
#23380 0x00007ffda112ff80 in lean::erase_irrelevant_fn::visit(lean::expr const&) ()
#23381 0x00007ffda11365c0 in lean::erase_irrelevant_fn::visit_lambda_core(lean::expr, bool) ()
#23382 0x00007ffda113555f in lean::erase_irrelevant_fn::decidable_to_bool_cases(lean::buffer<lean::expr, 16ull> const&) ()
#23383 0x00007ffda1131c2a in lean::erase_irrelevant_fn::visit_cases_on(lean::expr const&, lean::buffer<lean::expr, 16ull>&) ()
#23384 0x00007ffda1130870 in lean::erase_irrelevant_fn::visit_app(lean::expr const&) ()
#23385 0x00007ffda112ffb9 in lean::erase_irrelevant_fn::visit(lean::expr const&) ()
#23386 0x00007ffda1131370 in lean::erase_irrelevant_fn::visit_let(lean::expr) ()
#23387 0x00007ffda112ff80 in lean::erase_irrelevant_fn::visit(lean::expr const&) ()
#23388 0x00007ffda112f84d in lean::erase_irrelevant_core(lean::environment const&, lean::local_ctx const&, lean::expr const&) ()
#23389 0x00007ffda10fbed0 in lean::erase_irrelevant(lean::environment const&, lean::expr const&) ()
```
It seems like the compiler is trying to reduce the condition of the if expression and fails.
This is related to the `#eval` example since the code for `Float`'s `reprPrec` also contains such a condition which, after inlining, becomes a constant expression.
